config/routes.rb
#Листинг 3.5: Маршруты для действий home и help в контроллере StaticPages. config/routes.rb 

#Листинг 3.37: Установка корневого маршрута на страницу Home. config/routes.rb
#Листинг 5.22: Маршруты для статических страниц. config/routes.rb 
Rails.application.routes.draw do
root 'static_pages#home'  

get 'signup'  => 'users#new'

  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'signup'  => 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
def about
  end
def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
#Листинг 4.2: Определение хелпера full_title. app/helpers/application_helper.rb

module ApplicationHelper

  # Возвращает полный заголовок на основе заголовка страницы.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- #Листинг 5.11: Партиал для подвала сайта. app/views/layouts/_footer.html.erb
Листинг 5.24: Партиал подвала со ссылками. app/views/layouts/_footer.html.erb -->
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Febr_20</a>
    by <a href="http://www.michaelhartl.com/">ASF</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
#Листинг 5.10: Партиал для заголовка сайта. app/views/layouts/_header.html.erb
#Листинг 5.23: Партиал заголовка со ссылками. app/views/layouts/_header.html.erb 
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
#Листинг 5.9: Партиал для HTML shim. app/views/layouts/_shim.html.erb

<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!--#Листинг 3.32: Макет сайта учебного приложения. ЗЕЛЕНЫЙ app/views/layouts/application.html.erb
#Листинг 4.1: Макет сайта учебного приложения. app/views/layouts/application.html.erb
#Листинг 4.3: Шаблон сайта с хелпером full_title. ЗЕЛЕНЫЙ app/views/layouts/application.html.erb

Листинг 5.1: Шаблон сайта с добавленными структурами. app/views/layouts/application.html.erb
Листинг 5.8: Макет сайта с партиалами для таблицы стилей и заголовка. app/views/layouts/application.html.erb-->




<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
<%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
#Листинг 3.19: Код для страницы About. ЗЕЛЕНЫЙ app/views/static_pages/about.html.erb
#Листинг 3.31: Представление для страницы About с заголовком на основе встроенного Ruby. ЗЕЛЕНЫЙ app/views/static_pages/about.html.erb
#Листинг 3.35: Страница About с удаленной HTML-структурой. ЗЕЛЕНЫЙ app/views/static_pages/about.html.erb

<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<!--
#Листинг 4.6: Home-страница без индивидуального заголовка страницы. ЗЕЛЕНЫЙ app/views/static_pages/home.html.erb
Листинг 5.2: Home-страница со ссылкой на страницу регистрации. app/views/static_pages/home.html.erb 
Листинг 5.20: Представление для Contact-страницы. ЗЕЛЕНЫЙ app/views/static_pages/contact.html.erb -->

<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact (38)095-403-68-16
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
#Листинг 3.10: Доработка HTML для страницы Help. app/views/static_pages/help.html.erb
#Листинг 3.30: Представление для страницы Help с заголовком на основе встроенного Ruby. ЗЕЛЕНЫЙ app/views/static_pages/help.html.erb

<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/#help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<!--
#Листинг 4.6: Home-страница без индивидуального заголовка страницы. ЗЕЛЕНЫЙ app/views/static_pages/home.html.erb
Листинг 5.2: Home-страница со ссылкой на страницу регистрации. app/views/static_pages/home.html.erb 
Листинг 5.34: Связывание кнопки со страницей регистрации. app/views/static_pages/home.html.erb -->

<h1>Febr_20 shielded-shelf-40331.herokuapp.com/19-57 </h1>
    <p>
<div class="center jumbotron">
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

</div>
~/ch05_filling-in-layout branch master<p>
</p>
<%= link_to image_tag("241084701.gif", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
#Листинг 5.31:Листинг 
5.35: Начальная страница регистрации (заглушка). app/views/users/new.html.erb

<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>